### ISSUE TITLE
Adding frosted-ui to my project

### ISSUE THREAD

**Issue by noobCode-69** [whopio/frosted-ui#214]
### Link to the code that reproduces this issue or a replay of the bug

No link

### To Reproduce

1. I added frosted-ui to my nextjs , tailwind , ts codebase as stated in the docs
2. But when I import Theme to wrap my app around it 
3. I get this error 

<img width="1081" alt="image" src="https://github.com/user-attachments/assets/81af98fa-865a-4d97-aca5-a7a96b4eedd8">
 

### Current vs. Expected behavior

It should work fine

### Verify canary release

- [x] I verified that the issue exists in the latest Frosted canary release

**Comment by b-nnett** [comment]
Experiencing the same, when attempting to use the DatePicker on the latest version.

**Comment by zx-xch** [comment]
I am experiencing the same exact problem

**Comment by g-delmo** [comment]
@arturbien check this out

**Comment by arturbien** [comment]
@noobCode-69 @b-nnett @zx-xch can you provide a simple reproduction in codesandbox?

**Comment by noobCode-69** [comment]
> @noobCode-69 @b-nnett @zx-xch can you provide a simple reproduction in codesandbox?

@arturbien I just installed using npm as given in the docs , I was using react with vite . As soon I imported theme in application I got the above error

Thanks

**Comment by b-nnett** [comment]
@arturbien https://codesandbox.io/p/live/38ae3e77-310f-49d1-ae7e-506ea62b9b77. Add and initialise in layout and it breaks.

**Comment by b-nnett** [comment]
Bump. @arturbien

**Comment by noobCode-69** [comment]
any update on this @arturbien

**Comment by arturbien** [comment]
@b-nnett was trying to access the codesandbox but it's not available
<img width="577" alt="Screenshot 2024-10-21 at 11 54 33" src="https://github.com/user-attachments/assets/b7a16a3c-5dcb-4582-bbbc-a9ebf92351c1">

**Comment by b-nnett** [comment]
Yeah, I don't care anymore, I just won't use frosted if you guys cba spending 2 minutes making your own sandbox or replying within a week lol.

**Comment by arturbien** [comment]
@b-nnett @noobCode-69 @zx-xch this issue should be fixed now in `0.0.1-canary.47` #217
